apiVersion: v2
name: yet-another-cloudwatch-exporter
description: Yet Another Cloudwatch Exporter
type: application
version: 0.6.0
appVersion: "v0.36.1-alpha"
home: https://github.com/nerdswords/yet-another-cloudwatch-exporter
sources:
- https://github.com/nerdswords/yet-another-cloudwatch-exporter
keywords:
- aws
- cloudwatch
- prometheus
- exporter
- yet-another
- yace
